git:
  depth: 1

language: java

matrix:
  include:
    - os: linux
      dist: trusty
    - os: osx

sudo: true

addons:
  apt:
    packages:
      - rpm
      - oracle-java8-installer

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew tap caskroom/cask ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install brew-cask ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew cask install java ; fi
  - set JAVA_OPTS=-XX:MaxPermSize=1024m -Xmx1512m -Dfile.encoding=UTF-8 -Dprism.verbose=true -Djavafx.verbose=true -Dquantum.verbose=true
  - set JAVA_TOOL_OPTIONS=-Dfile.encoding=UTF-8

script:
  - ./gradlew -Pheadless=True check -Dzw.username=$ZDS_USERNAME -Dzw.password=$ZDS_PASSWORD --info
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./gradlew fatJar ; fi

after_success:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./gradlew jacocoTestReport coveralls; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then scripts/upload_deb.sh $BINTRAY_KEY ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then scripts/upload_rpm.sh $BINTRAY_KEY ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then scripts/upload_jar.sh $BINTRAY_KEY ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then scripts/upload_dmg.sh $BINTRAY_KEY ; fi

