version: '{build}'

environment:
  TERM: dumb
  matrix:
    - JAVA_HOME: C:\Program Files\Java\jdk1.8.0
    - JAVA_HOME: C:\Program Files (x86)\Java\jdk1.8.0
install:
  - set PATH=%JAVA_HOME%\bin;%PATH%
  - echo %PATH%
  - gradlew.bat clean
  - set JAVA_OPTS=-XX:MaxPermSize=1024m -Xmx1512m -Dfile.encoding=UTF-8 
  - set JAVA_TOOL_OPTIONS=-Dfile.encoding=UTF-8 

  
build_script:
  - gradlew.bat -u -i clean assemble

artifacts:
  - path: build\distributions\ZestWriter
    name: "zest-writer-for-windows"
    type: zip
  - path: build\distributions\ZestWriter\app\zest-writer-0.4.0.jar
    name: "zest-writer-jar"
    type: zip

on_failure:
  - echo Somebody setup us the bomb
