version: '{build}'

environment:
  TERM: dumb
  matrix:
    - JAVA_HOME: C:\Program Files\Java\jdk1.8.0
    - JAVA_HOME: C:\Program Files (x86)\Java\jdk1.8.0
install:
  - set PATH=%JAVA_HOME%\bin;%PATH%
  - echo %PATH%
  - gradlew.bat clean
  - set JAVA_OPTS=-XX:MaxPermSize=1024m -Xmx1512m
  
build_script:
  - gradlew.bat -u -i clean assemble

artifacts:
  - path: build\distributions
    name: "zest-writer-for-windows"
    type: zip
 
on_failure:
  - echo Somebody setup us the bomb
